### ISSUE TITLE
more types of questions?

### ISSUE THREAD

**Issue by macliems** [fabiandev/angular-quiz-app#17]
Really really REALLY nice, this quiz!!!!

Anyone working on one with more types of questions, like simple text input or fill in the blanks?

**Comment by fabiandev** [comment]
Thanks @macliems! Currently I'm not working on such an improvement, but I'm considering implementing more types of questions in the future.

**Comment by fabiandev** [comment]
I've added the ability to add question types more easily in the [question-types](../tree/question-types) branch. I will revisit the changes soon and will add some documentation.

Of course I'd appreciate any feedback. I'll keep you posted!

**Comment by fabiandev** [comment]
I've added a basic walk through on how to add answers and questions to the bottom of the [readme](../tree/question-types#extending) of the [question-types](../tree/question-types) branch. Also the example from this step-by-step guide has been added in the branch [question-types-example](../tree/question-types-example).
