### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by projectoblio** [fabiandev/angular-quiz-app#21]
I get no errors when building. I see "server started on port 5000". But when I navigate to localhost:5000, it says the page cannot be connected to ("unexpectedly closed the connection").

I also deployed this project to Heroku in case it was my wifi / firewall causing the issue. Here, it says "the page redirected you too many times" when I try to access the successful build. 

Any clue what is happening here?

**Comment by projectoblio** [comment]
I wonder if I need to set my redirect URI in the spotify API settings? Do you know what settings I should provide other than a client ID and client Secret inside the spotify dev console?

**Comment by fabiandev** [comment]
I think the issue here is the local https redirect. Does it work for you if you comment out this line?

https://github.com/fabiandev/angular-quiz-app/blob/cc251cc54ec7e759d65481eab1021f1c92c6c7b4/server/index.js#L38

**Comment by cpbuckingham** [comment]
@fabiandev - I am currently having this issue as well. I commented out the line you mentioned with no fix. I am following the readme and building successfully, but when I navigate to 5000 I am seeing the same issue as the poster. Thanks!

**Comment by fabiandev** [comment]
Did you either re-build, or started it with the dev server? Just to make sure that commented out line has been applied.

**Comment by cpbuckingham** [comment]
@fabiandev - that did it for me! Thanks!
