### ISSUE TITLE
just a question...

### ISSUE THREAD

**Issue by kasparov112000** [fabiandev/angular-quiz-app#22]
First and Foremost, thank you for such an awesome repo, learning about a bunch of new concepts you applied there...my question:  you applied the hidden tag on 

`<question-host *ngFor="let question of questions" [question]="question" hidden></question-host>`

I am reverse engeneering, I was able to get the app running but it won't show unless I remove the hidden attribute and if I do all 10 questions get displayed....I am not using any of the animations...

**Comment by fabiandev** [comment]
I would need to have a closer look, but from what you are saying I think that this is causing the issue:

> I am not using any of the animations...

The animations show and hide the questions in [`question.component.ts`](https://github.com/fabiandev/angular-quiz-app/blob/master/src/js/components/quiz/questions/question.component.ts)

Does it work if you change `this._animator.show(this._elementRef.nativeElement)` to e.g., `this._elementRef.nativeElement.removeAttribute('hidden')` [here](https://github.com/fabiandev/angular-quiz-app/blob/master/src/js/components/quiz/questions/question.component.ts#L149) and `addAttribute('hidden')` [here](https://github.com/fabiandev/angular-quiz-app/blob/master/src/js/components/quiz/questions/question.component.ts#L162)?
